const CONFIG = {
  business: {
    name: "Skoopka",
    tagline: {
      ru: "Скупка золота и ценностей в Ташкенте",
      uz: "Toshkentda oltin va qimmatbaho buyumlar qabul qilinadi",
    },
    description: {
      ru: "Профессиональная скупка золота и ювелирных изделий в районе Юнусабад, Ташкент",
      uz: "Toshkent, Yunusobod tumanida professional oltin va zargarlik buyumlari qabul",
    },
  },

  contact: {
    phone: "+998 97 773 01 79",
    phoneRaw: "+998977730179",
    telegram: "@skoopka",
    telegramUrl: "https://t.me/skoopka",
  },

  location: {
    city: {
      ru: "Ташкент",
      uz: "Toshkent",
    },
    district: {
      ru: "Юнусабад",
      uz: "Yunusobod",
    },
    address: {
      ru: "г. Ташкент, район Юнусабад",
      uz: "Toshkent shahar, Yunusobod tumani",
    },
    landmark: {
      ru: "",
      uz: "",
    },
    mapIframeSrc: "https://yandex.ru/map-widget/v1/?ll=69.294065%2C41.368603&z=17&pt=69.294065%2C41.368603%2Cpm2rdm",
  },

  hours: {
    weekdays: {
      label: { ru: "Пн – Пт", uz: "Du – Ju" },
      time: "9:00 – 18:00",
    },
    weekend: {
      label: { ru: "Суббота", uz: "Shanba" },
      time: "10:00 – 15:00",
    },
  },

  seo: {
    siteUrl: "https://skoopka.uz",
    keywords: {
      ru: [
        // Основные
        "скупка золота Ташкент",
        "сдать золото Ташкент",
        "продать золото Ташкент",
        "купить золото Ташкент",
        "скупка золота Юнусабад",
        "сдать золото Юнусабад",
        "продать золото Юнусабад",
        "приём золота Ташкент",
        "приём золота Юнусабад",
        "где сдать золото Ташкент",
        "где продать золото Ташкент",
        "скупка золота срочно Ташкент",
        // Слитки и монеты
        "скупка золотых слитков Ташкент",
        "скупка инвестиционного золота Ташкент",
        "скупка банковского золота Ташкент",
        "скупка золотых монет Ташкент",
        "скупка советских монет золото",
        "скупка червонцев Ташкент",
        "скупка памятных монет золото",
        // Лом
        "скупка золотого лома Ташкент",
        "скупка лома золота дорого",
        "скупка лома золота 585",
        "скупка лома золота 750",
        "сдать золотой лом Ташкент",
        // По пробе
        "скупка золота 375",
        "скупка золота 500",
        "скупка золота 583",
        "скупка золота 585",
        "скупка золота 750",
        "скупка золота 958",
        "скупка золота 999",
        // Серебро
        "скупка серебра Ташкент",
        "скупка серебра 925 Ташкент",
        "скупка серебра 875 Ташкент",
        "скупка серебра 800 Ташкент",
        "сдать серебро Ташкент",
        "продать серебро Ташкент",
        "скупка серебряных украшений Ташкент",
        "скупка серебряных монет Ташкент",
        // Смежные
        "оценка золота Ташкент",
        "курс золота Ташкент",
        "цена золота Ташкент сегодня",
        "скупка драгоценных металлов Ташкент",
        "скупка золота дорого Ташкент",
        "скупка золота выгодно Ташкент",
        "скупка золота без документов",
        "скупка платины Ташкент",
        "ломбард золото Ташкент",
      ].join(", "),
      uz: [
        "Toshkentda oltin qabul",
        "oltin sotish Toshkent",
        "oltin sotib olish Toshkent",
        "Yunusobodda oltin qabul",
        "oltin qabul markazi Toshkent",
        "oltin baholash Toshkent",
        "oltin narxi Toshkent bugun",
        "oltin kurs Toshkent",
        "qayerda oltin sotsa boladi Toshkent",
        "tez oltin qabul Toshkent",
        "qimmat oltin qabul Toshkent",
        // Слитки и монеты
        "oltin qo'yma qabul Toshkent",
        "investitsion oltin qabul",
        "bank oltini qabul Toshkent",
        "oltin tanga qabul Toshkent",
        "sovet tangalari oltin qabul",
        "chervonets qabul Toshkent",
        // Лом
        "oltin chiqit qabul Toshkent",
        "oltin chiqit qimmat qabul",
        "Yunusobodda oltin chiqit qabul",
        // По пробе
        "oltin 375 qabul",
        "oltin 585 qabul",
        "oltin 750 qabul",
        "oltin 999 qabul",
        // Серебро
        "kumush qabul Toshkent",
        "kumush 925 qabul Toshkent",
        "kumush 875 qabul Toshkent",
        "kumush sotish Toshkent",
        "kumush zargarlik qabul",
        // Смежные
        "qimmatbaho metallar qabul Toshkent",
        "oltin lombard Toshkent",
        "oltin hujjatsiz qabul",
        "platina qabul Toshkent",
        "Yunusobodda oltin sotish",
        "oltin qabul markazi Yunusobod",
        "oltin uzuk qabul",
        // Sotib olish
        "oltin sotib olish Toshkent",
        "oltin sotib olamiz Toshkent",
        "oltin sotib olinadi Toshkent",
        "oltin xarid qilish Toshkent",
        "oltin xarid qilamiz Toshkent",
        "kumush sotib olish Toshkent",
        "kumush xarid qilish Toshkent",
        "oltin qo'yma sotib olish",
        "oltin tanga sotib olish",
        "oltin chiqit sotib olish",
        "qimmatbaho metallar sotib olish Toshkent",
        "Yunusobodda oltin sotib olish",
        // Tilla
        "tilla qabul Toshkent",
        "tilla sotish Toshkent",
        "tilla sotib olish Toshkent",
        "Toshkentda tilla qabul",
        "Yunusobodda tilla qabul",
        "tilla qo'yma qabul",
        "tilla tanga qabul",
        "tilla chiqit qabul",
        "tilla baholash Toshkent",
        "tilla narxi Toshkent",
        "tilla kurs Toshkent",
        "tilla 585 qabul",
        "tilla 750 qabul",
        "tilla 375 qabul",
        "tilla xarid qilish Toshkent",
        "tilla sotib olamiz Toshkent",
        "oltin zanjir qabul",
        "oltin bilaguzuk qabul",
        "oltin isirg'a qabul",
        "oltin chiqit qabul",
        "oltin qo'yma qabul",
        "oltin tanga qabul",
        "qimmatbaho buyumlar qabul Toshkent",
        "oltin lombard Toshkent",
        "kumush qabul Toshkent",
        "oltin narxi Toshkent",
        "tez oltin qabul Toshkent",
        "qimmat oltin qabul Toshkent",
      ].join(", "),
    },
  },

  jsonLd: {
    priceRange: "$$",
    currenciesAccepted: "UZS",
    paymentAccepted: "Cash",
  },
};
